elasticsearch:
  image: elasticsearch:2.3.3
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
logstash:
    image: logstash:2.3.2
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
        - ./logstash/config:/etc/logstash/conf.d
    ports:
        - "5000:5000"
        - "8080:8080"
    links:
        - elasticsearch
kibana:
    build: kibana/
    volumes:
        - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
    ports:
        - "5601:5601"
    links:
        - elasticsearch
